apiVersion: v1
kind: Service
metadata:
  name: ztdc
  namespace: zero-trust
  labels:
    app: ztdc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "ssl"
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - port: 443
    targetPort: 8443
    protocol: TCP
    name: https
  - port: 9443
    targetPort: 9443
    protocol: TCP
    name: metrics
  selector:
    app: ztdc

---
apiVersion: v1
kind: Service
metadata:
  name: ztdc-headless
  namespace: zero-trust
  labels:
    app: ztdc
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 8443
    targetPort: 8443
    protocol: TCP
    name: https
  selector:
    app: ztdc